const planetData = [
  {
    name: "Mercurious",
    system: "Solar System",
    type: "Rocky",
    category: "Solar System",
    description: "The smallest planet and the closest planet to the Sun.",
    distance: 0.00001,
    temperature: 167,
    travelDays: 120,
    price: 150000,
    image: "/images/planets/mercury.png",
    featured: false
  },
  {
    name: "VeAnus",
    system: "Solar System",
    type: "Rocky",
    category: "Solar System",
    description: "A volcanic world covered by a thick and extremely hot atmosphere.",
    distance: 0.000004,
    temperature: 464,
    travelDays: 90,
    price: 175000,
    image: "/images/planets/venus.png",
    featured: true
  },
  {
    name: "Urath",
    system: "Solar System",
    type: "Rocky",
    category: "Solar System",
    description: "Our home planet and the only known world with life.",
    distance: 0,
    temperature: 15,
    travelDays: 0,
    price: 0,
    image: "/images/planets/earth.png",
    featured: false
  },
  {
    name: "Mars",
    system: "Solar System",
    type: "Rocky",
    category: "Solar System",
    description: "The Red Planet, known for its deserts, volcanoes and canyons.",
    distance: 0.000024,
    temperature: -63,
    travelDays: 210,
    price: 250000,
    image: "/images/planets/mars.png",
    featured: true
  },
  {
    name: "Jupiler",
    system: "Solar System",
    type: "Gas Giant",
    category: "Solar System",
    description: "The largest planet, famous for its Great Red Spot.",
    distance: 0.000066,
    temperature: -110,
    travelDays: 730,
    price: 600000,
    image: "/images/planets/jupiter.png",
    featured: true
  },
  {
    name: "Saturn",
    system: "Solar System",
    type: "Gas Giant",
    category: "Solar System",
    description: "A gas giant surrounded by a spectacular system of icy rings.",
    distance: 0.000135,
    temperature: -140,
    travelDays: 1460,
    price: 850000,
    image: "/images/planets/saturn.png",
    featured: true
  },
  {
    name: "UrAnus",
    system: "Solar System",
    type: "Ice Giant",
    category: "Solar System",
    description: "A pale blue ice giant rotating almost completely on its side.",
    distance: 0.000288,
    temperature: -195,
    travelDays: 2920,
    price: 1200000,
    image: "/images/planets/uranus.png",
    featured: false
  },
  {
    name: "Neptune",
    system: "Solar System",
    type: "Ice Giant",
    category: "Solar System",
    description: "A distant blue world with some of the fastest winds known.",
    distance: 0.00046,
    temperature: -200,
    travelDays: 4380,
    price: 1500000,
    image: "/images/planets/neptune.png",
    featured: true
  },
  {
    name: "Proxima Centauri b",
    system: "Proxima Centauri",
    type: "Rocky",
    category: "Exoplanet",
    description: "The closest known exoplanet to Earth, orbiting a red dwarf star.",
    distance: 4.24,
    temperature: -39,
    travelDays: 1800,
    price: 4500000,
    image: "/images/planets/proxima-centauri-b.png",
    featured: true
  },
  {
    name: "TRAPPIST-1e",
    system: "TRAPPIST-1",
    type: "Rocky",
    category: "Exoplanet",
    description: "An Earth-sized world located in the habitable zone of its star.",
    distance: 40.7,
    temperature: -27,
    travelDays: 4200,
    price: 12500000,
    image: "/images/planets/trappist-1e.png",
    featured: true
  },
  {
    name: "TRAPPIST-1f",
    system: "TRAPPIST-1",
    type: "Rocky",
    category: "Exoplanet",
    description: "A cold Earth-sized planet that may contain significant water.",
    distance: 40.7,
    temperature: -54,
    travelDays: 4300,
    price: 12000000,
    image: "/images/planets/trappist-1f.png",
    featured: false
  },
  {
    name: "Kepler-186f",
    system: "Kepler-186",
    type: "Rocky",
    category: "Exoplanet",
    description: "One of the first Earth-sized planets found in a habitable zone.",
    distance: 582,
    temperature: -85,
    travelDays: 6800,
    price: 28000000,
    image: "/images/planets/kepler-186f.png",
    featured: true
  },
  {
    name: "Kepler-452b",
    system: "Kepler-452",
    type: "Super-Earth",
    category: "Exoplanet",
    description: "A possible rocky super-Earth orbiting a Sun-like star.",
    distance: 1400,
    temperature: -8,
    travelDays: 9200,
    price: 48000000,
    image: "/images/planets/kepler-452b.png",
    featured: true
  },
  {
    name: "Kepler-22b",
    system: "Kepler-22",
    type: "Super-Earth",
    category: "Exoplanet",
    description: "A large planet orbiting within the habitable zone of its star.",
    distance: 635,
    temperature: -11,
    travelDays: 7100,
    price: 30000000,
    image: "/images/planets/kepler-22b.png",
    featured: false
  },
  {
    name: "TOI-700 d",
    system: "TOI-700",
    type: "Rocky",
    category: "Exoplanet",
    description: "An Earth-sized planet orbiting within its star's habitable zone.",
    distance: 101.4,
    temperature: -69,
    travelDays: 5100,
    price: 17500000,
    image: "/images/planets/toi-700-d.png",
    featured: true
  },
  {
    name: "TOI-700 e",
    system: "TOI-700",
    type: "Rocky",
    category: "Exoplanet",
    description: "A terrestrial planet located near the inner edge of the habitable zone.",
    distance: 101.4,
    temperature: -4,
    travelDays: 5000,
    price: 18000000,
    image: "/images/planets/toi-700-e.png",
    featured: false
  },
  {
    name: "K2-18 b",
    system: "K2-18",
    type: "Mini-Neptune",
    category: "Exoplanet",
    description: "A potentially ocean-rich world with a hydrogen-heavy atmosphere.",
    distance: 124,
    temperature: -8,
    travelDays: 5400,
    price: 19500000,
    image: "/images/planets/k2-18-b.png",
    featured: true
  },
  {
    name: "LHS 1140 b",
    system: "LHS 1140",
    type: "Super-Earth",
    category: "Exoplanet",
    description: "A dense super-Earth that may contain water or a frozen ocean.",
    distance: 48.8,
    temperature: -43,
    travelDays: 4500,
    price: 14000000,
    image: "/images/planets/lhs-1140-b.png",
    featured: true
  },
  {
    name: "55 Cancri e",
    system: "55 Cancri",
    type: "Lava World",
    category: "Exoplanet",
    description: "An extremely hot super-Earth that may have oceans of molten lava.",
    distance: 41,
    temperature: 2000,
    travelDays: 4400,
    price: 10500000,
    image: "/images/planets/55-cancri-e.png",
    featured: false
  },
  {
    name: "HD 189733 b",
    system: "HD 189733",
    type: "Hot Jupiter",
    category: "Exoplanet",
    description: "A deep-blue gas giant with extreme winds and glass-like rain.",
    distance: 64.5,
    temperature: 930,
    travelDays: 4700,
    price: 15500000,
    image: "/images/planets/hd-189733-b.png",
    featured: true
  },
  {
    name: "WASP-12 b",
    system: "WASP-12",
    type: "Hot Jupiter",
    category: "Exoplanet",
    description: "An ultra-hot gas giant slowly being consumed by its star.",
    distance: 1410,
    temperature: 2250,
    travelDays: 9400,
    price: 50000000,
    image: "/images/planets/wasp-12-b.png",
    featured: false
  },
  {
    name: "Kepler-16b",
    system: "Kepler-16",
    type: "Gas Giant",
    category: "Exoplanet",
    description: "A circumbinary planet that travels around two stars.",
    distance: 245,
    temperature: -85,
    travelDays: 6100,
    price: 24000000,
    image: "/images/planets/kepler-16b.png",
    featured: true
  },
  {
    name: "GJ 1214 b",
    system: "GJ 1214",
    type: "Mini-Neptune",
    category: "Exoplanet",
    description: "A warm, cloudy world that may have a water-rich interior.",
    distance: 48,
    temperature: 230,
    travelDays: 4600,
    price: 14500000,
    image: "/images/planets/gj-1214-b.png",
    featured: false
  },
  {
    name: "Gliese 667 Cc",
    system: "Gliese 667 C",
    type: "Super-Earth",
    category: "Exoplanet",
    description: "A super-Earth orbiting within the habitable zone of a nearby star.",
    distance: 23.6,
    temperature: 4,
    travelDays: 3500,
    price: 9000000,
    image: "/images/planets/gliese-667-cc.png",
    featured: true
  }
];

module.exports = planetData
